stages:
  - build
  - deploy
image: python:latest

before_script:
  - pip install poetry

build:
  stage: build

  script:
    - API_ENDPOINT=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages
    - poetry config repositories.gitlab $API_ENDPOINT/pypi
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish --build --repository gitlab

deploy:
  stage: deploy
  needs: [build]
  trigger:
    project: slurpit.io/slurpit-netbox-docker
    branch: release

