variables:
  PY_VERSION: "3.10"
  REPO_PACKAGE_API: ${CI_API_V4_URL}/projects/netyce%2fpypi/packages
  NETYCE_PYPI: ${REPO_PACKAGE_API}/pypi
  PYPI: ${REPO_PACKAGE_API}/pypi/simple/

#lint:
#  image: alpine/flake8
#  stage: build
#  script:
#    - flake8 backmiko tests
#

build:
  image: "${PUBLIC_REGISTRY}/poe3:3.11"
  variables:
    TOKEN: $PYPI_TOKEN
  script:
    - remove-pypi
    - poetry config repositories.netyce $NETYCE_PYPI
    - poetry publish --build --repository netyce -u "gitlab-ci-token" -p "${CI_JOB_TOKEN}"

deploy:
  needs: [build]
  trigger:
    project: netyce/slurpit-netbox-docker
    branch: release

